# Generated by Django 5.0.14 on 2025-05-04 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0002_receita"),
    ]

    operations = [
        migrations.CreateModel(
            name="Produto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("descricao", models.TextField(blank=True)),
                ("preco", models.DecimalField(decimal_places=2, max_digits=10)),
                ("estoque", models.IntegerField()),
                (
                    "imagem_pequena",
                    models.ImageField(
                        blank=True, null=True, upload_to="produtos/thumbs/"
                    ),
                ),
                (
                    "imagem_grande",
                    models.ImageField(
                        blank=True, null=True, upload_to="produtos/grandes/"
                    ),
                ),
                ("data_criacao", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
