# Generated by Django 5.0.14 on 2025-05-04 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0003_produto"),
    ]

    operations = [
        migrations.AddField(
            model_name="produto",
            name="ordem",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
